/**
 * Copyright 2009 - 2020 J&#246;rgen Lundgren
 * 
 * This file is part of org.macroing.cel4j.
 * 
 * org.macroing.cel4j is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * org.macroing.cel4j is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with org.macroing.cel4j. If not, see <http://www.gnu.org/licenses/>.
 */
package org.macroing.cel4j.php.model;

import java.lang.reflect.Field;//TODO: Add Javadocs!
import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

import org.macroing.cel4j.util.Document;

//TODO: Add Javadocs!
public final class PDocument {
	private final List<PClass> pClasses;
	private final List<PInterface> pInterfaces;
	private final List<String> uses;
	private final PBlock pBlock;
	private String namespace;
	private boolean isGeneratingComment;
	
	////////////////////////////////////////////////////////////////////////////////////////////////////
	
//	TODO: Add Javadocs!
	public PDocument() {
		this.pClasses = new ArrayList<>();
		this.pInterfaces = new ArrayList<>();
		this.uses = new ArrayList<>();
		this.pBlock = new PBlock();
		this.namespace = "";
		this.isGeneratingComment = false;
	}
	
	////////////////////////////////////////////////////////////////////////////////////////////////////
	
//	TODO: Add Javadocs!
	public Document write() {
		return write(new Document());
	}
	
//	TODO: Add Javadocs!
	public Document write(final Document document) {
		return write(document, false);
	}
	
//	TODO: Add Javadocs!
	public Document write(final Document document, final boolean isAligningPConsts) {
		final List<PClass> pClasses = getPClasses();
		final List<PInterface> pInterfaces = getPInterfaces();
		final List<String> uses = getUses();
		
		final PBlock pBlock = getPBlock();
		
		final boolean hasPBlockLines = !pBlock.isEmpty();
		final boolean hasPClasses = pClasses.size() > 0;
		final boolean hasPInterfaces = pInterfaces.size() > 0;
		
		final boolean isGeneratingComment = isGeneratingComment();
		
		final String namespace = getNamespace();
		
		document.line("<?php");
		document.indent();
		
		if(isGeneratingComment) {
			document.linef("/**");
			document.linef(" * The PHP source code was generated by CEL4J PHP at %s.", LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
			document.linef(" */");
			document.linef("");
		}
		
		if(!namespace.isEmpty()) {
			document.linef("namespace %s;", namespace);
			document.linef("");
		}
		
		if(!uses.isEmpty()) {
			for(int i = 0; i < uses.size(); i++) {
				final String useA = uses.get(i);
				final String useB = uses.get(i + 1 < uses.size() ? i + 1 : i);
				
				document.linef("use %s;", useA);
				
				final String[] useAParts = useA.split("\\\\");
				final String[] useBParts = useB.split("\\\\");
				
				if(useAParts.length > 0 && useBParts.length > 0 && !useAParts[0].equals(useBParts[0])) {
					document.line();
				}
			}
			
			document.line();
		}
		
		for(int i = 0; i < pInterfaces.size(); i++) {
			final PInterface pInterfaceA = pInterfaces.get(i);
			final PInterface pInterfaceB = pInterfaces.get(i + 1 < pInterfaces.size() ? i + 1 : i);
			
			pInterfaceA.write(document);
			
			if(pInterfaceA != pInterfaceB) {
				document.line();
				document.line("////////////////////////////////////////////////////////////////////////////////////////////////////");
				document.line();
			}
		}
		
		if((hasPClasses || hasPBlockLines) && hasPInterfaces) {
			document.line();
			document.line("////////////////////////////////////////////////////////////////////////////////////////////////////");
			document.line();
		}
		
		for(int i = 0; i < pClasses.size(); i++) {
			final PClass pClassA = pClasses.get(i);
			final PClass pClassB = pClasses.get(i + 1 < pClasses.size() ? i + 1 : i);
			
			pClassA.write(document, isAligningPConsts);
			
			if(pClassA != pClassB) {
				document.line();
				document.line("////////////////////////////////////////////////////////////////////////////////////////////////////");
				document.line();
			}
		}
		
		if(hasPClasses && hasPBlockLines) {
			document.line();
			document.line("////////////////////////////////////////////////////////////////////////////////////////////////////");
			document.line();
		}
		
		pBlock.write(document);
		
		return document;
	}
	
//	TODO: Add Javadocs!
	public Document write(final File file) {
		return write(file, false);
	}
	
//	TODO: Add Javadocs!
	public Document write(final File file, final boolean isAligningPConsts) {
		try {
			final Document document = write(new Document(), isAligningPConsts);
			
			file.getParentFile().mkdirs();
			
			Files.write(file.toPath(), document.toString().getBytes("UTF-8"), StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE);
			
			return document;
		} catch(final IOException e) {
			throw new UncheckedIOException(e);
		}
	}
	
//	TODO: Add Javadocs!
	public List<PClass> getPClasses() {
		return new ArrayList<>(this.pClasses);
	}
	
//	TODO: Add Javadocs!
	public List<PInterface> getPInterfaces() {
		return new ArrayList<>(this.pInterfaces);
	}
	
//	TODO: Add Javadocs!
	public List<String> getUses() {
		return new ArrayList<>(this.uses);
	}
	
//	TODO: Add Javadocs!
	public PBlock getPBlock() {
		return this.pBlock;
	}
	
//	TODO: Add Javadocs!
	public String getNamespace() {
		return this.namespace;
	}
	
//	TODO: Add Javadocs!
	public boolean isGeneratingComment() {
		return this.isGeneratingComment;
	}
	
//	TODO: Add Javadocs!
	public void addPClass(final PClass pClass) {
		this.pClasses.add(Objects.requireNonNull(pClass, "pClass == null"));
	}
	
//	TODO: Add Javadocs!
	public void addPInterface(final PInterface pInterface) {
		this.pInterfaces.add(Objects.requireNonNull(pInterface, "pInterface == null"));
	}
	
//	TODO: Add Javadocs!
	public void addUse(final String use) {
		this.uses.add(Objects.requireNonNull(use, "use == null"));
	}
	
//	TODO: Add Javadocs!
	public void removePClass(final PClass pClass) {
		this.pClasses.remove(Objects.requireNonNull(pClass, "pClass == null"));
	}
	
//	TODO: Add Javadocs!
	public void removePInterface(final PInterface pInterface) {
		this.pInterfaces.remove(Objects.requireNonNull(pInterface, "pInterface == null"));
	}
	
//	TODO: Add Javadocs!
	public void removeUse(final String use) {
		this.uses.remove(Objects.requireNonNull(use, "use == null"));
	}
	
//	TODO: Add Javadocs!
	public void setGeneratingComment(final boolean isGeneratingComment) {
		this.isGeneratingComment = isGeneratingComment;
	}
	
//	TODO: Add Javadocs!
	public void setNamespace(final String namespace) {
		this.namespace = Objects.requireNonNull(namespace, "namespace == null");
	}
	
	////////////////////////////////////////////////////////////////////////////////////////////////////
	
//	TODO: Add Javadocs!
	public static String toNamespace(final String... names) {
		return Arrays.asList(names).stream().filter(name -> !name.isEmpty()).collect(Collectors.joining("\\"));
	}
}